### ISSUE TITLE
First impression of the app should communicate that the app is about books

### ISSUE THREAD

**Issue by MarkusZoppelt** [MarkusZoppelt/LeniBooks#17]
Maybe show an image header with books or implement skeuomorphic icons

**Comment by Twinf0x** [comment]
Tried out a new style for the book tiles in the AllBooksPage. The intention was to give the tiles a more book-like appearance. What do you think about it? Any feedback is welcome.

You can take a look at the redesign by checking out the branch [feature/all-books-redesign](https://github.com/MarkusZoppelt/LeniBooks/tree/feature/all-books-redesign)
