### ISSUE TITLE
Show books as books sitting on a shelf

### ISSUE THREAD

**Issue by MarkusZoppelt** [MarkusZoppelt/LeniBooks#8]

**Comment by MarkusZoppelt** [comment]
Inspiration: https://pin.it/6p4L9RT

**Comment by Twinf0x** [comment]
What do you think about  a neumorphic design approach? Apple seems to go that way with its Soft UI. I have to say I like it quite a bit and it seems to be somewhere in between skeumorphic design and flat design.

[Example1](https://creativemarket.com/delightful.design/4568144-Neumorphic-Soft-UI-Kit-NEU?u=delightful.design) [Example2](https://lh5.googleusercontent.com/SDlCyM3Xi-eLaujdQ1PXBzd7T-xwM9EjHrsdUhtKXB9Ta2F3EyzUCMQdfg1CfBxhsrCr5w71BYK_XeInvMG-q1VYCSiFYJy81YzUe0xiaB452UBTuORLkiQEjH3WhShgcAhtoByP)

**Comment by MarkusZoppelt** [comment]
Looks awesome! Let's see how we can implement this design approach

**Comment by MarkusZoppelt** [comment]
https://pub.dev/packages/flutter_neumorphic
